version: "3.9"
services:
  db:
    image: postgres:15.4-alpine3.18
    container_name: kanko-key-db
    env_file:
      - ./environment/db-variables.env
    volumes:
      - ./dbdata:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:${DB_PORT}"

  pgadmin4:
    image: dpage/pgadmin4
    container_name: kanko-key-pgadmin4
    ports:
      - "${PGADMIN_PORT}:80"
    volumes:
      - ./pgadmin4:/var/lib/pgadmin
    env_file:
      - ./environment/pgadmin4-variables.env
    depends_on:
      - db

  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        WORKDIR: ${WORKDIR}
    container_name: kanko-key-api
    env_file:
      - ./environment/api-variables.env
    tty: true
    command: ./gradlew clean bootRun
    volumes:
      - .:/${WORKDIR}
    ports:
      - "${API_PORT}:${API_PORT}"
      - "${DEBUG_PORT}:${DEBUG_PORT}"
    depends_on:
      - db